### ISSUE TITLE
Github.com opfes not visible

### ISSUE THREAD

**Issue by MichaelAkkermans** [TimvanSteenbergen/onepasswordforeverysite#49]
When logging in to github the opfes options are not visible when changing the password.

**Comment by TimvanSteenbergen** [comment]
Indeed. Reason is the password-field being hidden upon arriving on that page. After selecting 'Account' the password-element does not get loaded, but it becomes visible. This does not trigger the Opfes popup.

After  selecting 'Account' and refreshing the page, the opfes popup does show up.

After  selecting 'Account' and refreshing the page, and then selecting another menu option (for instance 'Email') when the password gets hidden again, the Opfes popup does not get removed, stays visible.

Since this is all related to hiding and showing password-elements, this issue will get delt with in issue 48.
